version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
